/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'CHURNAI',systemName:'知华客户流失预警 AI 平台',englishName:'CUSTOMER CHURN AI',theme:{primary:'#3d5a80',dark:'#24344d',accent:'#e88b4a'},
 workspace:'客户成功中心 / 智能经营组',fieldWorkspace:'华东大区 / 客户成功一组',period:'2026-08-15 · 每日评分',liveText:'客户信号于 10:28 更新',fieldContextLabel:'当前组合',fieldContext:'重点续约客户',fieldUser:'顾遥',fieldRole:'客户成功经理',adminUser:'沈砚',adminRole:'客户运营负责人',
 adminTitle:'客户留存运营中心',adminBreadcrumb:'客户智能 / 留存态势',adminSubtitle:'融合交易、服务、回款和互动信号，提前识别流失风险并安排分层挽留动作。',exportAction:'导出留存报告',createAction:'新建挽留任务',
 chartTitle:'客户留存闭环趋势',chartSubtitle:'本月挽回率 / 目标值',chartLabels:['01日','05日','09日','13日','17日','21日','25日','29日','31日'],loadTitle:'客户组合风险分布',loadSubtitle:'高风险客户占当前责任组合比例',recordsTitle:'重点客户挽留任务',recordsSubtitle:'按流失概率、收入影响和合同窗口排序',issueTitle:'需要处理的客户信号',issueSubtitle:'来自复购下降、客诉、回款和续约节点',
 recordName:'挽留任务',itemName:'客户账户',unitName:'责任团队',batchName:'风险信号',planName:'触达项',doneName:'已完成',exceptionName:'阻塞',unitLabel:'项',
 listBreadcrumb:'客户留存 / 挽留任务',listSubtitle:'将交易、服务和互动信号汇总为可解释的客户流失优先级。',listSummary:[['管理客户','486'],['本月预警','57'],['高风险','12',true],['已挽回','31']],tabs:['全部','待触达','跟进中','待确认','已归档'],
 fieldBreadcrumb:'客户工作台 / 成功经理',fieldTitle:'客户挽留工作台',fieldSubtitle:'负责客户 68 家 · 今日触达 11 项 · 待处理预警 4 条',fieldSecondary:'查看客户旅程',reportAction:'提交跟进结论',fieldNoticeTitle:'客户信号同步正常',fieldNotice:'核心行为覆盖率 95.4%',
 steps:['信号汇聚','风险评分','原因解释','人工触达','结果复盘'],documentAction:'查看客户档案',printAction:'导出挽留行动单',resourceCardTitle:'客户数据资源',resourceValueLabel:'接入账户',resourceHealthLabel:'信号健康度',quickSubtitle:'常用客户入口',
 quickActions:[['流失诊断','/shopfloor/report','交易、服务与互动证据'],['客户档案','/shopfloor/material','合同、联系人和服务履历'],['数据资源','/shopfloor/resources','CRM、工单和模型版本'],['风险升级','/shopfloor/andon','重大客诉与续约阻塞协同']],
 reportDefaults:[4,1],reportTitle:'客户跟进反馈',reportSubtitle:'记录触达结果、核心诉求和下一步挽留动作。',reportSuccess:'客户跟进反馈已提交',reportPlaceholder:'填写客户反馈、流失原因、价值诉求和承诺动作',reportFootnote:'提交后进入客户运营负责人复核队列',ruleTitle:'客户挽留合规门禁',ruleSubtitle:'CHURN-AI · V1.0',rules:[['营销触达','遵守客户授权'],['价格承诺','销售共同批准'],['模型原因','保留证据链'],['结果复盘','续约后执行',true]],fieldTotals:[['68','负责客户'],['4','待处理预警'],['11','今日触达'],['95.4%','信号覆盖率']],
 adminMenus:[['/admin','home','留存运营中心'],['/admin/work-orders','order','挽留任务'],['/admin/samples','box','客户账户'],['/admin/schedule','calendar','触达计划'],['/admin/methods','process','评分策略'],['/admin/reviews','quality','结果复核'],['/admin/resources','machine','数据资源'],['/admin/report','chart','留存分析']],fieldMenus:[['/shopfloor','home','挽留工作台'],['/shopfloor/report','report','跟进反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','客户档案'],['/shopfloor/resources','machine','信号状态'],['/shopfloor/andon','risk','风险升级',4]],
 moduleTitles:{tasks:['我的挽留任务','查看概率、收入影响和触达状态'],material:['客户账户档案','查看交易、合同、服务与联系人'],resources:['客户数据中心','管理 CRM、工单和留存模型'],andon:['客户风险升级','提交重大客诉和续约阻塞'],samples:['客户账户台账','统一管理客户分层和价值贡献'],schedule:['客户触达计划','协调销售、服务与管理层拜访'],methods:['流失评分策略','维护特征、阈值和挽留模板'],reviews:['挽留结果复核','记录确认、驳回和补充触达'],report:['客户留存分析','分析流失原因、挽回率和收入影响']},
 tagline:'在客户离开之前，看见真实的风险信号',storyTitle:'把客户沉默，<br/>变成有依据的挽留行动',storyText:'连接交易、服务与互动数据，帮助客户成功团队提前介入并坚持人工沟通。',pattern:[2,4,7,9,12,15,18,21,24,27,30],loginStats:[['486','管理客户'],['95.4%','信号覆盖率'],['12','高风险客户']],loginTitle:'客户留存运营中心',adminDemo:'风险 / 收入 / 挽回',fieldDemo:'客户 / 触达 / 反馈'}
export const records=[{no:'CR-260815-018',name:'远山智能制造',code:'CUS-1088',unit:'华东客户成功组',group:'战略客户',plan:9,done:5,exception:2,due:'08-15',batch:'复购+客诉',status:'跟进中',progress:56,priority:'P1'},{no:'CR-260815-021',name:'青禾零售集团',code:'CUS-2031',unit:'零售行业组',group:'成长客户',plan:8,done:3,exception:1,due:'08-16',batch:'活跃度下降',status:'待触达',progress:38,priority:'P2'},{no:'CR-260815-026',name:'北辰物流科技',code:'CUS-3106',unit:'交通行业组',group:'重点客户',plan:10,done:2,exception:3,due:'08-16',batch:'回款+续约',status:'待触达',progress:20,priority:'P1'},{no:'CR-260814-015',name:'瀚海医药供应链',code:'CUS-1762',unit:'医药行业组',group:'稳定客户',plan:7,done:7,exception:0,due:'08-14',batch:'服务满意度',status:'已归档',progress:100,priority:'P3'},{no:'CR-260815-031',name:'云际新能源',code:'CUS-2268',unit:'华南客户成功组',group:'成长客户',plan:11,done:7,exception:1,due:'08-17',batch:'使用频率',status:'跟进中',progress:64,priority:'P2'}]
export const resources=[{code:'CRM-01',name:'客户交易与合同中心',unit:'客户数据组',status:'运行中',health:98,value:'486',valueUnit:'户',note:'近二十四小时数据完整率 99.2%'},{code:'MODEL-02',name:'客户流失预测模型',unit:'客户智能组',status:'复核中',health:94,value:'v3.1',valueUnit:'',note:'12 家客户进入高风险队列'},{code:'VOC-03',name:'工单与客户之声连接器',unit:'服务运营组',status:'预警',health:88,value:'73',valueUnit:'条',note:'3 条客诉标签等待确认'}]
export const reviews=[{no:'RV-260815-032',title:'远山制造流失原因复核',type:'P1 挽留',detail:'概率 0.91 · 沈砚',result:'待确认'},{no:'RV-260815-011',title:'青禾零售价值回顾',type:'续约方案',detail:'3 项客户诉求 · 顾遥',result:'通过'},{no:'RV-260814-018',title:'北辰物流回款风险',type:'证据补充',detail:'缺少采购决策人反馈',result:'异常'}]
export const adminMetrics=[['管理客户','486','年度合同额 2.8 亿元','blue'],['高风险客户','12','其中 5 家为战略客户','red'],['本月挽回','31','挽回收入 1,260 万元','green'],['待批方案','7','需要销售共同确认','orange']]
export const fieldMetrics=[['我的任务','9','4 项 P1','blue'],['今日已触达','11','全部记录客户反馈','green'],['待处理预警','4','2 项涉及续约','orange'],['信号覆盖率','95.4%','较上周提升 1.1%','slate']]
export const chartActual=[52,55,58,62,66,70,73,77,81],chartTarget=[55,58,61,64,68,72,76,80,84]
export const loads=[['战略客户',82,'高风险 5 家'],['重点客户',68,'高风险 4 家'],['成长客户',54,'高风险 3 家'],['稳定客户',26,'暂无高风险']]
export const issues=[['续约','远山制造合同仅剩二十天','建议负责人和销售联合拜访','待批准'],['客诉','北辰物流连续三次交付投诉','服务改进计划尚未确认','处理中'],['活跃','云际新能源核心功能使用下降','安排产品培训与价值回顾','需协调']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
